---
title: "R DataStructure"
author: "wyy"
date: "2016-6-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Structure
1. vectro
2. matrix
3. data.frame
4. factor
5. list

### Vector

```{r vector}
rm(list = ls())
num <- c(1,2,3,4,5,6,7,8,9,10)
vec <- c(1:10)
strVec <- c("one", "two", "three")
logicVEC <- c(TRUE, FALSE, FALSE, TRUE)
# function
# mode
y <- vector(mode = 'logical', length = 10)
# sep
z1 <- seq(from = 1, to = 100, by = 4)
z2 <- seq(from = 1, to = 100, length = 20)
# rep
w1 <- rep(c(1,2,3), 3)
w2 <- rep(c(1,2,3), each = 2)

```

#### 1. algebra 
```{r}
rm(list = ls())
x <- c(1,2,3)
y <- c(5,4,-1)
x / y
x %% y
```

#### 2. index
```{r}
rm(list = ls())
y <- c(1:10)
y[c(4,5,6)]
y[-c(3:8)]
```

#### 3. all any which
```{r}
rm(list = ls())
x <- c(1,3,7,4,2,8,10,4,2,11)
any(x > 5)
all(x > 5)
which(x > 5)
```

#### 4. filtering subset
```{r}
rm(list = ls())
z <- c(5, 2, -3, 8, NA, 1)
subset(z, z*z > 8)
```

#### 5. ifelse

#### 6. name

### Matrix Array
```{r matrix}
rm(list = ls())
(m1 <- matrix(c(1:16), nrow = 4, ncol = 4))
(m2 <- matrix(c(1:16), nrow = 4, byrow = T))
dim(m1)
nrow(m1)
ncol(m1)
# function
x <- matrix(nrow = 3, ncol = 3)
y <- matrix(c(4,5,2,3), nrow = 2)
x[2:3,2:3] <- y
x
```

#### 1. algebra
```{r}
m %*% m
3 * m
m + m
```

#### 2. index

```{r}
m[, 2:3]
m[2:3,]
```

#### 3. apply


#### 4. add delete
```{r}
# c[] c[-]
# rbind cbind
#  <- ???┬И?ох
```

#### 5. avoid dimensions reducing
```{r}
rm(list = ls())
z <- matrix(c(1:4), nrow = 2)
r <- z[2,]
r
attributes(z)
str(z)
attributes(r)
str(r)
l <- z[2, , drop = FALSE]
attributes(l)
str(l)
r <- as.matrix(r)
attributes(r)
str(r)

```

#### 6. colnames rownames

### data.frame
```{r}
rm(list = ls())
dtname <- c('wyy', 'wtt', 'yhz', 'yyl', 'wj')
dtid <- c(3, 1, 5, 3, 6)
dta <- c('t', 'b', 't', 's', 's')
dtf <- data.frame(dtname, dtid, dta, stringsAsFactors = FALSE)
```
#### 2. index
```{r index}
dtf$dtid
dtf[1,]
```

### factor
```{r factor}

```














